# spawnverse/config.py
MODEL_REGISTRY = {
    # Tier 1: fastest, cheapest — summarize / classify specialist
    "llama-3.1-8b-instant": {
        "tier": 1,
        "context_window": 128_000,
        "cost_input_per_1k":  0.05,
        "cost_output_per_1k": 0.08,
        "reward_mult":  1.5,
        "penalty_mult": 0.8,
        "skills": {
            "summarize":  0.88,
            "classify":   0.82,
            "extract":    0.78,
            "format":     0.75,
            "reason":     0.35,
            "synthesize": 0.20,
            "plan":       0.18,
            "code":       0.25,
            "research":   0.20,
        },
    },
    # Tier 2: compact compound — good all-rounder at low cost
    "groq/compound-mini": {
        "tier": 2,
        "context_window": 32_000,
        "cost_input_per_1k":  0.08,
        "cost_output_per_1k": 0.12,
        "reward_mult":  1.3,
        "penalty_mult": 0.7,
        "skills": {
            "summarize":  0.80,
            "classify":   0.85,
            "extract":    0.82,
            "format":     0.78,
            "reason":     0.50,
            "synthesize": 0.40,
            "plan":       0.38,
            "code":       0.45,
            "research":   0.38,
        },
    },
    # Tier 3: scout — efficient MoE, strong reasoning + code
    "meta-llama/llama-4-scout-17b-16e-instruct": {
        "tier": 3,
        "context_window": 131_072,
        "cost_input_per_1k":  0.11,
        "cost_output_per_1k": 0.34,
        "reward_mult":  1.1,
        "penalty_mult": 0.6,
        "skills": {
            "summarize":  0.72,
            "classify":   0.72,
            "extract":    0.78,
            "format":     0.78,
            "reason":     0.75,
            "synthesize": 0.65,
            "plan":       0.65,
            "code":       0.78,
            "research":   0.68,
        },
    },
    # Tier 4: Qwen3-32b — strong multilingual + reasoning
    "qwen/qwen3-32b": {
        "tier": 4,
        "context_window": 32_768,
        "cost_input_per_1k":  0.20,
        "cost_output_per_1k": 0.60,
        "reward_mult":  0.9,
        "penalty_mult": 0.5,
        "skills": {
            "summarize":  0.75,
            "classify":   0.75,
            "extract":    0.80,
            "format":     0.80,
            "reason":     0.88,
            "synthesize": 0.82,
            "plan":       0.80,
            "code":       0.85,
            "research":   0.80,
        },
    },
    # Tier 5a: Groq Compound — full agentic compound model
    "groq/compound": {
        "tier": 5,
        "context_window": 128_000,
        "cost_input_per_1k":  0.28,
        "cost_output_per_1k": 0.50,
        "reward_mult":  0.8,
        "penalty_mult": 0.45,
        "skills": {
            "summarize":  0.78,
            "classify":   0.78,
            "extract":    0.82,
            "format":     0.82,
            "reason":     0.92,
            "synthesize": 0.90,
            "plan":       0.90,
            "code":       0.88,
            "research":   0.88,
        },
    },
    # Tier 5b: llama-3.3-70b — best open text model on Groq
    "llama-3.3-70b-versatile": {
        "tier": 5,
        "context_window": 128_000,
        "cost_input_per_1k":  0.59,
        "cost_output_per_1k": 0.79,
        "reward_mult":  0.7,
        "penalty_mult": 0.4,
        "skills": {
            "summarize":  0.78,
            "classify":   0.78,
            "extract":    0.82,
            "format":     0.82,
            "reason":     1.00,
            "synthesize": 0.95,
            "plan":       0.92,
            "code":       0.90,
            "research":   0.92,
        },
    },
}

SKILL_KEYWORDS = {
    "summarize":  ["summarize", "summary", "condense", "brief", "recap", "overview", "tldr", "shorten"],
    "classify":   ["classify", "categorize", "label", "tag", "identify type", "detect type", "sort"],
    "extract":    ["extract", "parse", "pull out", "retrieve", "scrape", "collect", "gather", "fetch", "get"],
    "format":     ["format", "template", "structure", "organise", "arrange", "convert", "transform", "render"],
    "reason":     ["reason", "infer", "deduce", "analyse", "analyze", "evaluate", "judge", "assess", "why",
                   "compare", "comparison", "contrast", "versus", " vs ", "differences", "pros and cons"],
    "synthesize": ["synthesize", "synthesis", "combine", "merge", "integrate", "compile", "consolidate", "aggregate", "unify"],
    "plan":       ["plan", "itinerary", "schedule", "roadmap", "strategy", "steps", "outline", "design"],
    "code":       ["code", "script", "function", "program", "implement", "build", "develop", "debug", "refactor"],
    "research":   ["research", "investigate", "study", "explore", "compare", "review", "survey", "benchmark"],
}

DEFAULT_CONFIG = {
    "model":                        "llama-3.3-70b-versatile",
    "max_depth":                    2,
    "wave1_agents":                 4,
    "wave2_agents":                 4,
    "parallel":                     True,
    "max_parallel":                 4,
    "timeout_depth0":               120,
    "timeout_depth1":               90,
    "timeout_depth2":               60,
    "retry_failed":                 True,
    "min_spawn_score":              0.4,
    "token_budget":                 80_000,
    "per_agent_tokens":             8_000,
    "per_agent_tokens_synthesis":   16_000,
    "rate_limit_retry":             5,
    "rate_limit_wait":              3,
    "drift_warn":                   0.45,
    "quality_min":                  0.45,
    "sandbox_enabled":              True,
    "sandbox_cpu_sec":              60,
    "sandbox_ram_mb":               512,
    "sandbox_fsize_mb":             10,
    "guardrail_code":               True,
    "guardrail_output":             True,
    "guardrail_semantic":           True,
    "vector_db_enabled":            False,
    "vector_db_path":               "spawnverse_vectordb",
    "rag_top_k":                    5,
    "rag_chunk_size":               800,
    "rag_chunk_overlap":            100,
    "output_format":                "structured",
    "show_stdout":                  True,
    "show_messages":                True,
    "show_progress":                True,
    "db_path":                      "spawnverse.db",
    "agents_dir":                   ".spawnverse_agents",
    "external_apis":                False,
    "external_api_key":             {},
    "soul_quality_threshold":       0.7,
    "soul_min_runs":                3,
    "soul_constitution_max_chars":  800,
    # Model routing
    "model_routing":                False,
    "routing_explore_c":            1.2,
    "drift_threshold":              0.65,
    "routing_tier_floor_enabled":   True,
    "routing_context_safety_mult":  3,
    # groq/compound — 413s on agent prompts; decommissioned models — removed from Groq API
    "agent_model_blacklist":        [
        "groq/compound",
        "llama-3.1-70b-versatile",
        "deepseek-r1-distill-llama-70b",
    ],
}
